src := "cpp/cgh_engine.cpp"
lib_dir := "lib"
lib_name := "cgh_engine.dylib"

inc := "-Icpp -Icpp/third_party/boost_math -Icpp/third_party/nlohmann_json"

build:
    mkdir -p {{lib_dir}}
    clang++ -std=c++20 -dynamiclib -O3 {{inc}} -o {{lib_dir}}/{{lib_name}} {{src}}

clean:
    rm -rf {{lib_dir}}/{{lib_name}}